env:
  seed: 2
  name: WorkflowScheduling-v0
  traffic_pattern: CONSTANT
  gamma: 2.0
policy:
  name: model_workflow
  state_num: 8
  action_num: 1
  discrete_action: True
  add_gru: False
optim:
  name: ga_uberai
  population_size: 100
  generation_num: 3000
  truncation_selection: True
  top_T: 20 # top T individuals become the parents of the next generation
  elite_candidate_size: 5
  addition_eval_elite_candidate: 5
  elitism: 1
  input_running_mean_std: False  # fixme: check True setting
  input_clip: False
  input_clip_value_min: Null
  input_clip_value_max: Null
  sigma_init: 0.002 # noise standard deviation
  sigma_decay: 0.999
  learning_rate: 0.001
  learning_rate_decay: 0.9999
  weight_decay: 0